### ISSUE TITLE
AttributeError: 'ModbusIOException' object has no attribute 'exception_code'

### ISSUE THREAD

**Issue by WillCodeForCats** [WillCodeForCats/solaredge-modbus-multi#156]
```
This error originated from a custom integration.

Logger: custom_components.solaredge_modbus_multi
Source: custom_components/solaredge_modbus_multi/hub.py:684
Integration: SolarEdge Modbus Multi Device (documentation, issues)
First occurred: 6:39:24 AM (1 occurrences)
Last logged: 6:39:24 AM

Unexpected error fetching SolarEdge Coordinator data: 'ModbusIOException' object has no attribute 'exception_code'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/solaredge_modbus_multi/__init__.py", line 178, in _async_update_data
    return await self._hub.async_refresh_modbus_data()
  File "/config/custom_components/solaredge_modbus_multi/hub.py", line 329, in async_refresh_modbus_data
    await self._hass.async_add_executor_job(inverter.read_modbus_data)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/solaredge_modbus_multi/hub.py", line 684, in read_modbus_data
    if inverter_data.exception_code == ModbusExceptions.IllegalAddress:
AttributeError: 'ModbusIOException' object has no attribute 'exception_code'
```

_Originally posted by @purcell-lab in https://github.com/WillCodeForCats/solaredge-modbus-multi/issues/137#issuecomment-1296357432_

**Comment by WillCodeForCats** [comment]
[Release v2.2.6-pre.4](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.2.6-pre.4)
